CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'pending', created_at TEXT DEFAULT (datetime('now')), class_name TEXT NOT NULL DEFAULT '', department TEXT DEFAULT '', password_reset INTEGER DEFAULT 0, achievements TEXT NOT NULL DEFAULT '[]', token_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS issues (id INTEGER PRIMARY KEY AUTOINCREMENT, location TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL DEFAULT '待处理', submitted_by TEXT NOT NULL, updated_by TEXT, contact TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), updated_at TEXT, notes TEXT DEFAULT '', image_url TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS announcements (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, content TEXT NOT NULL, image_url TEXT DEFAULT '', status TEXT DEFAULT '已通过', reviewed_by TEXT DEFAULT '', reviewed_at TEXT, reject_reason TEXT DEFAULT '', created_by TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS finance (id INTEGER PRIMARY KEY AUTOINCREMENT, image_url TEXT NOT NULL, tags TEXT DEFAULT '[]', notes TEXT DEFAULT '', type TEXT NOT NULL DEFAULT '支出', amount REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT '待完成', created_by TEXT NOT NULL, completed_by TEXT, created_at TEXT DEFAULT (datetime('now')), completed_at TEXT, department TEXT DEFAULT '', fund_type TEXT DEFAULT '基金账单', internal_activity INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, image_url TEXT NOT NULL, status TEXT NOT NULL DEFAULT '待审核', reject_reason TEXT, created_by TEXT NOT NULL, reviewed_by TEXT, created_at TEXT DEFAULT (datetime('now')), reviewed_at TEXT);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS comments (id INTEGER PRIMARY KEY AUTOINCREMENT, target_type TEXT NOT NULL, target_id INTEGER NOT NULL, content TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS polls (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'open', require_name INTEGER NOT NULL DEFAULT 0, min_role TEXT, created_by TEXT NOT NULL, total_votes INTEGER NOT NULL DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), allowed_classes TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS poll_questions (id INTEGER PRIMARY KEY AUTOINCREMENT, poll_id INTEGER NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, options TEXT DEFAULT '[]', image_url TEXT DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0, max_length INTEGER NOT NULL DEFAULT 1000);
CREATE TABLE IF NOT EXISTS poll_responses (id INTEGER PRIMARY KEY AUTOINCREMENT, poll_id INTEGER NOT NULL, user_id INTEGER, voter_name TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), ip TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS poll_answers (id INTEGER PRIMARY KEY AUTOINCREMENT, response_id INTEGER NOT NULL, question_id INTEGER NOT NULL, answer TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chat_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, user_name TEXT NOT NULL, content TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'text', system_data TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS feed_comments (id INTEGER PRIMARY KEY AUTOINCREMENT, feed_id INTEGER NOT NULL, user_name TEXT NOT NULL, content TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT NOT NULL, contact TEXT DEFAULT '', page TEXT DEFAULT '', turnstile_bypass INTEGER DEFAULT 0, section TEXT DEFAULT '', version TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS hall_bookings (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL, purpose TEXT NOT NULL, applicant TEXT NOT NULL, user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', reviewed_by TEXT DEFAULT '', reviewed_at TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS duty_staff (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER DEFAULT 0, department TEXT NOT NULL, class TEXT NOT NULL, name TEXT NOT NULL, password TEXT DEFAULT '', is_active INTEGER DEFAULT 1, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS duty_schedule (id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, staff_a_id INTEGER NOT NULL, staff_b_id INTEGER NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS duty_attendance (id INTEGER PRIMARY KEY AUTOINCREMENT, schedule_id INTEGER NOT NULL, staff_id INTEGER NOT NULL, period TEXT NOT NULL, sign_in_time TEXT, sign_out_time TEXT, duration_sec INTEGER DEFAULT 0, status TEXT DEFAULT 'pending', score_absent REAL DEFAULT 0, score_duration REAL DEFAULT 0, is_manual INTEGER DEFAULT 0, modified_by TEXT DEFAULT '', modified_reason TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS duty_score_record (id INTEGER PRIMARY KEY AUTOINCREMENT, staff_id INTEGER NOT NULL, date TEXT NOT NULL, period TEXT NOT NULL, score REAL NOT NULL, reason TEXT DEFAULT '', recorder TEXT DEFAULT 'system', is_cancelled INTEGER DEFAULT 0, cancel_reason TEXT DEFAULT '', cancel_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS duty_period_config (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL UNIQUE, slot_type TEXT NOT NULL, sort_order INTEGER NOT NULL, start_time TEXT DEFAULT '08:00', auto_absent_min INTEGER DEFAULT 10);
CREATE TABLE IF NOT EXISTS activities (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, location TEXT DEFAULT '', time TEXT NOT NULL, departments TEXT DEFAULT '', need_volunteers INTEGER NOT NULL DEFAULT 0, created_by TEXT NOT NULL, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS activity_volunteers (id INTEGER PRIMARY KEY AUTOINCREMENT, activity_id INTEGER NOT NULL, member_name TEXT NOT NULL, department TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS features (id INTEGER PRIMARY KEY AUTOINCREMENT, key TEXT UNIQUE NOT NULL, name TEXT NOT NULL, description TEXT DEFAULT '', icon TEXT DEFAULT 'bell', globally_enabled INTEGER DEFAULT 0, invite_mode TEXT DEFAULT 'manual', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS user_feature_responses (user_id INTEGER NOT NULL, feature_key TEXT NOT NULL, status TEXT DEFAULT 'pending', invited_at TEXT, responded_at TEXT, PRIMARY KEY(user_id, feature_key));
CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, body TEXT DEFAULT '', link TEXT DEFAULT '', icon TEXT DEFAULT '', is_read INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS announcement_images (id INTEGER PRIMARY KEY AUTOINCREMENT, announcement_id INTEGER NOT NULL, image_url TEXT NOT NULL, sort_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS captcha_used (nonce TEXT PRIMARY KEY, expire INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_users_name ON users(name);
CREATE INDEX IF NOT EXISTS idx_issues_created ON issues(created_at);
CREATE INDEX IF NOT EXISTS idx_issues_status ON issues(status);
CREATE INDEX IF NOT EXISTS idx_announcements_created ON announcements(created_at);
CREATE INDEX IF NOT EXISTS idx_announce_images_aid ON announcement_images(announcement_id);
CREATE INDEX IF NOT EXISTS idx_finance_created ON finance(created_at);
CREATE INDEX IF NOT EXISTS idx_finance_department ON finance(department);
CREATE INDEX IF NOT EXISTS idx_reviews_created ON reviews(created_at);
CREATE INDEX IF NOT EXISTS idx_comments_target ON comments(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_by ON comments(created_by);
CREATE INDEX IF NOT EXISTS idx_polls_created ON polls(created_at);
CREATE INDEX IF NOT EXISTS idx_poll_questions_pid ON poll_questions(poll_id);
CREATE INDEX IF NOT EXISTS idx_poll_responses_pid ON poll_responses(poll_id);
CREATE INDEX IF NOT EXISTS idx_poll_responses_poll_user ON poll_responses(poll_id, user_id);
CREATE INDEX IF NOT EXISTS idx_poll_responses_poll_ip ON poll_responses(poll_id, ip);
CREATE INDEX IF NOT EXISTS idx_poll_answers_rid ON poll_answers(response_id);
CREATE INDEX IF NOT EXISTS idx_poll_answers_qid ON poll_answers(question_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_type_created ON chat_messages(type, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON chat_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_feed_comments_fid ON feed_comments(feed_id);
CREATE INDEX IF NOT EXISTS idx_feedback_created ON feedback(created_at);
CREATE INDEX IF NOT EXISTS idx_hall_bookings_date ON hall_bookings(date);
CREATE INDEX IF NOT EXISTS idx_hall_bookings_status ON hall_bookings(status);
CREATE INDEX IF NOT EXISTS idx_hall_bookings_user_id ON hall_bookings(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_duty_schedule_date ON duty_schedule(date);
CREATE INDEX IF NOT EXISTS idx_duty_attendance_schedule ON duty_attendance(schedule_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_duty_attendance_unique ON duty_attendance(schedule_id, staff_id, period);
CREATE INDEX IF NOT EXISTS idx_duty_score_record_staff ON duty_score_record(staff_id);
CREATE INDEX IF NOT EXISTS idx_activities_created ON activities(created_at);
CREATE INDEX IF NOT EXISTS idx_activity_volunteers_aid ON activity_volunteers(activity_id);
CREATE INDEX IF NOT EXISTS idx_activity_volunteers_activity_member ON activity_volunteers(activity_id, member_name);
CREATE INDEX IF NOT EXISTS idx_features_key ON features(key);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read, created_at);
