name = "yali-tongban"
# Vite 构建产物目录（原为 public，迁移到 Vite 多页后指向 dist）
pages_build_output_dir = "dist"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "yali-tongban-db"
database_id = "a7fb5f2d-4ea5-4727-9253-137845ae7835"
